### ISSUE TITLE
XSS in search.php

### ISSUE THREAD

**Issue by jgj212** [digioz/php#26]
Here is a xss vulnerability in search.php about parameter search_term.

POC:
```
http://your-web-root/uestbook/1.8.0/search.php?search_term="><script>alert(1);</script><"
```

This poc will pop a window in FireFox browser.

**Comment by digioz** [comment]
Thank you for reporting this issue. This issue has already been fixed in later versions of the guestbook (currently version 2.0.3). You can try a demo of the new version here:

https://www.digioz.com/demo/php/guestbook/

Please upgrade to the latest version and test again to verify the issue has been fully resolved. You can download the source code of the new version here:

https://github.com/digioz/php/tree/master/guestbook/2.0.3
